
--resetear todo
DO $$
DECLARE
    table_record RECORD;
    function_record RECORD;
    trigger_record RECORD;
     function_name TEXT;
BEGIN
    -- Eliminar todas las tablas
    FOR table_record IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public') LOOP
        EXECUTE 'DROP TABLE IF EXISTS public.' || table_record.table_name || ' CASCADE';
    END LOOP;

    -- Eliminar todas las funciones
     FOR function_name IN (SELECT routine_name FROM information_schema.routines WHERE specific_schema = 'public' AND routine_type = 'FUNCTION') LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS public.' || function_name || ' CASCADE';
    END LOOP;

    -- Eliminar todos los triggers
    FOR trigger_record IN (SELECT trigger_name FROM information_schema.triggers WHERE trigger_schema = 'public') LOOP
        EXECUTE 'DROP TRIGGER IF EXISTS public.' || trigger_record.trigger_name || ' ON ALL TABLES CASCADE';
    END LOOP;
END $$;



CREATE TABLE public.empresa (
    id bigint NOT NULL,
    nombre text NOT NULL,
    simbolomoneda text,
    iduseradmin bigint
);


ALTER TABLE public.empresa OWNER TO postgres;

--
-- TOC entry 271 (class 1259 OID 29561)
-- Name: asignarempresa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asignarempresa (
    id bigint NOT NULL,
    id_empresa bigint NOT NULL,
    id_usuario bigint
);


ALTER TABLE public.asignarempresa OWNER TO postgres;

--
-- TOC entry 272 (class 1259 OID 29564)
-- Name: asignarempresa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asignarempresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asignarempresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 29565)
-- Name: categorias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias (
    id bigint NOT NULL,
    descripcion text NOT NULL,
    color text,
    id_empresa bigint
);


ALTER TABLE public.categorias OWNER TO postgres;

--
-- TOC entry 274 (class 1259 OID 29570)
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 275 (class 1259 OID 29571)
-- Name: empresa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 29572)
-- Name: kardex; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kardex (
    id bigint NOT NULL,
    fecha date NOT NULL,
    tipo text,
    id_usuario bigint,
    id_producto bigint,
    cantidad double precision,
    id_empresa bigint,
    detalle text,
    estado bigint DEFAULT '1'::bigint
);


ALTER TABLE public.kardex OWNER TO postgres;

--
-- TOC entry 277 (class 1259 OID 29578)
-- Name: kardex_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kardex ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kardex_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 278 (class 1259 OID 29579)
-- Name: marca; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marca (
    id bigint NOT NULL,
    descripcion text NOT NULL,
    id_empresa bigint
);


ALTER TABLE public.marca OWNER TO postgres;

--
-- TOC entry 279 (class 1259 OID 29584)
-- Name: marca_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 29585)
-- Name: modulos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.modulos (
    id bigint NOT NULL,
    nombre text NOT NULL,
    "check" boolean DEFAULT false
);


ALTER TABLE public.modulos OWNER TO postgres;

--
-- TOC entry 281 (class 1259 OID 29591)
-- Name: modulos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.modulos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modulos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 282 (class 1259 OID 29592)
-- Name: permisos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permisos (
    id bigint NOT NULL,
    id_usuario bigint NOT NULL,
    idmodulo bigint
);


ALTER TABLE public.permisos OWNER TO postgres;

--
-- TOC entry 283 (class 1259 OID 29595)
-- Name: permisos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permisos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permisos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 284 (class 1259 OID 29596)
-- Name: productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    descripcion text NOT NULL,
    idmarca bigint,
    stock numeric,
    stock_minimo numeric,
    codigobarras text,
    codigointerno text,
    precioventa numeric,
    preciocompra numeric,
    id_categoria bigint,
    id_empresa bigint
);


ALTER TABLE public.productos OWNER TO postgres;

--
-- TOC entry 285 (class 1259 OID 29601)
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 286 (class 1259 OID 29602)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    nombres text DEFAULT 'generico'::text NOT NULL,
    nro_doc text DEFAULT '-'::text,
    telefono text DEFAULT '-'::text,
    direccion text DEFAULT '-'::text,
    fecharegistro date NOT NULL,
    estado text DEFAULT 'activo'::text,
    tipouser text NOT NULL,
    idauth text NOT NULL,
    tipodoc text DEFAULT '-'::text,
    correo text DEFAULT '-'::text
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 287 (class 1259 OID 29614)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);





--
-- TOC entry 3705 (class 2606 OID 29720)
-- Name: asignarempresa asignarempresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignarempresa
    ADD CONSTRAINT asignarempresa_pkey PRIMARY KEY (id);


--
-- TOC entry 3707 (class 2606 OID 29722)
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- TOC entry 3703 (class 2606 OID 29724)
-- Name: empresa empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);


--
-- TOC entry 3709 (class 2606 OID 29726)
-- Name: kardex kardex_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kardex
    ADD CONSTRAINT kardex_pkey PRIMARY KEY (id);


--
-- TOC entry 3711 (class 2606 OID 29728)
-- Name: marca marca_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT marca_pkey PRIMARY KEY (id);


--
-- TOC entry 3713 (class 2606 OID 29730)
-- Name: modulos modulos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modulos
    ADD CONSTRAINT modulos_pkey PRIMARY KEY (id);


--
-- TOC entry 3715 (class 2606 OID 29732)
-- Name: permisos permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_pkey PRIMARY KEY (id);


--
-- TOC entry 3717 (class 2606 OID 29734)
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- TOC entry 3719 (class 2606 OID 29736)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 3734 (class 2620 OID 29801)
-- Name: kardex eliminarkardextrigger; Type: TRIGGER; Schema: public; Owner: postgres
--


--create trigger

CREATE FUNCTION public.insertpermisos() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare item record;
begin
 if new.tipouser='superadmin' then
 insert into empresa(nombre,simbolomoneda,iduseradmin)
 values('Generica','S/.',new.id);
 end if;
 for item in
  select id from modulos
  loop
   if new.tipouser='superadmin' then
    insert into permisos(id_usuario,idmodulo)
    values(new.id,item.id);
   end if;
  end loop;
  return new;
end
$$;
CREATE FUNCTION public.insertpordefecto() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare item record;
begin
 insert into marca(descripcion,id_empresa)
 values('Generica',new.id);
 insert into categorias(descripcion,color,id_empresa)
 values('General','#FF5722',new.id);
 insert into asignarempresa(id_empresa,id_usuario)
 values(new.id,new.iduseradmin);

 insert into modulos(nombre)
 values('Salidas varias');
  insert into modulos(nombre)
 values('Productos');
  insert into modulos(nombre)
 values('Personal');
  insert into modulos(nombre)
 values('Tu empresa');
  insert into modulos(nombre)
 values('Categoria de productos');
  insert into modulos(nombre)
 values('Marca de productos');
  insert into modulos(nombre)
 values('Kardex');

 return new;
end
$$;
CREATE FUNCTION public.modificarstock() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare stockproducto numeric;
begin
  if new.tipo='entrada' then
      update productos
      set stock=stock+new.cantidad
      where id = new.id_producto;
  else
     select into stockproducto stock
     from productos
     where id = new.id_producto;
     if stockproducto > new.cantidad then
         update productos
         set stock=stock-new.cantidad
         where id = new.id_producto;
     else 
        raise exception 'Stock agotado para este producto';
     end if;
  end if;
  return new;
end;
$$;
CREATE FUNCTION public.eliminarkardexdisparado() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
   insert into kardex(fecha,tipo,id_usuario,id_producto,cantidad,id_empresa,detalle,estado)
   values (now(),old.tipo||'-anulado',old.id_usuario,old.id_producto,old.cantidad,old.id_empresa,old.detalle || '-anulado',0);

   update productos
   set stock = stock + old.cantidad
   where id = new.id_producto;
   return old;
end;
$$;


CREATE TRIGGER eliminarkardextrigger BEFORE DELETE ON public.kardex FOR EACH ROW EXECUTE FUNCTION public.eliminarkardexdisparado();


--
-- TOC entry 3735 (class 2620 OID 29802)
-- Name: kardex modificarstocktrigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER modificarstocktrigger AFTER INSERT ON public.kardex FOR EACH ROW EXECUTE FUNCTION public.modificarstock();


--
-- TOC entry 3736 (class 2620 OID 29803)
-- Name: usuarios permisostrigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER permisostrigger AFTER INSERT ON public.usuarios FOR EACH ROW EXECUTE FUNCTION public.insertpermisos();


--
-- TOC entry 3733 (class 2620 OID 29804)
-- Name: empresa pordefectotrigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER pordefectotrigger AFTER INSERT ON public.empresa FOR EACH ROW EXECUTE FUNCTION public.insertpordefecto();


--
-- TOC entry 3721 (class 2606 OID 29862)
-- Name: asignarempresa asignarempresa_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

CREATE FUNCTION public.mostrarempresaasignaciones(_id_usuario integer) RETURNS SETOF public.empresa
    LANGUAGE sql
    AS $$
SELECT
   empresa.*
FROM empresa
    inner join asignarempresa on asignarempresa.id_empresa=empresa.id inner join usuarios on asignarempresa.id_usuario=usuarios.id
WHERE
    asignarempresa.id_usuario=_id_usuario;
$$;


ALTER FUNCTION public.mostrarempresaasignaciones(_id_usuario integer) OWNER TO postgres;



CREATE FUNCTION public.mostrarkardexempresa(_id_empresa integer) RETURNS TABLE(id integer, descripcion text, fecha text, cantidad double precision, tipo text, detalle text, nombres text, stock numeric, estado integer)
    LANGUAGE sql
    AS $$
select kardex.id, productos.descripcion,kardex.fecha,kardex.cantidad,kardex.tipo,kardex.detalle,usuarios.nombres,productos.stock,kardex.estado from kardex inner join empresa on empresa.id=kardex.id_empresa inner join usuarios on usuarios.id=kardex.id_usuario inner join productos on productos.id= kardex.id_producto
where kardex.id_empresa=_id_empresa
$$;


ALTER FUNCTION public.mostrarkardexempresa(_id_empresa integer) OWNER TO postgres;


--
-- TOC entry 486 (class 1255 OID 29492)
-- Name: mostrarpersonal(integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.mostrarpersonal(_id_empresa integer) RETURNS TABLE(id integer, nombres text, tipouser text, estado text, correo text, nro_doc text, telefono text, direccion text, tipodoc text)
    LANGUAGE sql
    AS $$
select u.id,u.nombres,u.tipouser,u.estado,u.correo,u.nro_doc,u.telefono,u.direccion,u.tipodoc from asignarempresa inner join usuarios u on u.id=asignarempresa.id_usuario inner join empresa on empresa.id=asignarempresa.id_empresa
where asignarempresa.id_empresa=_id_empresa
$$;


ALTER FUNCTION public.mostrarpersonal(_id_empresa integer) OWNER TO postgres;

--
-- TOC entry 519 (class 1255 OID 29493)
-- Name: mostrarproductos(integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.mostrarproductos(_id_empresa integer) RETURNS TABLE(id integer, descripcion text, idmarca integer, stock numeric, stock_minimo numeric, codigobarras text, codigointerno text, precioventa numeric, preciocompra numeric, id_categoria integer, id_empresa integer, marca text, categoria text, color text)
    LANGUAGE sql
    AS $$
SELECT
    p.id, p.descripcion, p.idmarca, p.stock, p.stock_minimo,
    p.codigobarras, p.codigointerno, p.precioventa, p.preciocompra,
    p.id_categoria, p.id_empresa,
    m.descripcion AS marca,
    c.descripcion AS categoria,
    c.color
FROM
    productos p
    INNER JOIN categorias c ON c.id = p.id_categoria
    INNER JOIN marca m ON m.id = p.idmarca
WHERE
    p.id_empresa = _id_empresa;
$$;


ALTER FUNCTION public.mostrarproductos(_id_empresa integer) OWNER TO postgres;

--
-- TOC entry 487 (class 1255 OID 29494)
-- Name: reportproductosbajominimo(integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.reportproductosbajominimo(_id_empresa integer) RETURNS TABLE(id integer, descripcion text, stock numeric, stock_minimo numeric, codigobarras text, codigointerno text, precioventa numeric, preciocompra numeric, id_empresa integer)
    LANGUAGE sql
    AS $$
SELECT
    p.id, p.descripcion, p.stock, p.stock_minimo,
    p.codigobarras, p.codigointerno, p.precioventa, p.preciocompra, p.id_empresa
   
FROM
    productos p
WHERE
    p.id_empresa = _id_empresa and p.stock<=p.stock_minimo;
$$;


ALTER FUNCTION public.reportproductosbajominimo(_id_empresa integer) OWNER TO postgres;
ALTER TABLE ONLY public.asignarempresa
    ADD CONSTRAINT asignarempresa_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id);




CREATE FUNCTION public.buscarkardexempresa(_id_empresa integer, buscador text) RETURNS TABLE(id integer, descripcion text, fecha text, cantidad double precision, tipo text, detalle text, nombres text, stock numeric, estado integer)
    LANGUAGE sql
    AS $$
select kardex.id, productos.descripcion,kardex.fecha,kardex.cantidad,kardex.tipo,kardex.detalle,usuarios.nombres,productos.stock,kardex.estado from kardex inner join empresa on empresa.id=kardex.id_empresa inner join usuarios on usuarios.id=kardex.id_usuario inner join productos on productos.id= kardex.id_producto
where productos.descripcion ilike '%'||buscador||'%' and kardex.id_empresa=_id_empresa
$$;


ALTER FUNCTION public.buscarkardexempresa(_id_empresa integer, buscador text) OWNER TO postgres;

--
-- TOC entry 514 (class 1255 OID 29472)
-- Name: buscarpersonal(integer, text); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.buscarpersonal(_id_empresa integer, buscador text) RETURNS TABLE(id integer, nombres text, tipouser text, estado text, correo text, nro_doc text, telefono text, direccion text, tipodoc text)
    LANGUAGE sql
    AS $$
select u.id,u.nombres,u.tipouser,u.estado,u.correo,u.nro_doc,u.telefono,u.direccion,u.tipodoc from asignarempresa inner join usuarios u on u.id=asignarempresa.id_usuario inner join empresa on empresa.id=asignarempresa.id_empresa
where u.nombres ILIKE '%'||buscador||'%' and  asignarempresa.id_empresa=_id_empresa 
$$;


ALTER FUNCTION public.buscarpersonal(_id_empresa integer, buscador text) OWNER TO postgres;

--
-- TOC entry 482 (class 1255 OID 29473)
-- Name: buscarproductos(integer, text); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.buscarproductos(_id_empresa integer, buscador text) RETURNS TABLE(id integer, descripcion text, idmarca integer, stock numeric, stock_minimo numeric, codigobarras text, codigointerno text, precioventa numeric, preciocompra numeric, id_categoria integer, id_empresa integer, marca text, categoria text, color text)
    LANGUAGE sql
    AS $$
SELECT
    p.id, p.descripcion, p.idmarca, p.stock, p.stock_minimo,
    p.codigobarras, p.codigointerno, p.precioventa, p.preciocompra,
    p.id_categoria, p.id_empresa,
    m.descripcion AS marca,
    c.descripcion AS categoria,
    c.color
FROM
    productos p
    INNER JOIN categorias c ON c.id = p.id_categoria
    INNER JOIN marca m ON m.id = p.idmarca
WHERE
    p.descripcion ILIKE '%'||buscador||'%' and p.id_empresa = _id_empresa ;
$$;


ALTER FUNCTION public.buscarproductos(_id_empresa integer, buscador text) OWNER TO postgres;

--
-- TOC entry 483 (class 1255 OID 29474)
-- Name: contar_usuarios_por_empresa(integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.contar_usuarios_por_empresa(_id_empresa integer) RETURNS integer
    LANGUAGE plpgsql
    AS $$
DECLARE
    cantidad_usuarios INT;
BEGIN
    SELECT COUNT(*) INTO cantidad_usuarios
    FROM asignarempresa
    WHERE id_empresa = _id_empresa;

    RETURN cantidad_usuarios;
END;
$$;


ALTER FUNCTION public.contar_usuarios_por_empresa(_id_empresa integer) OWNER TO postgres;

--
-- TOC entry 477 (class 1255 OID 29475)
-- Name: editarmarca(text, integer, integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.editarmarca(_descripcion text, _idempresa integer, _id integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
   perform 1 from marca where descripcion =_descripcion and id_empresa=_idempresa and id!=_id;
   if found then
     raise exception 'Datos duplicados';
   else
     update marca set descripcion=_descripcion
     where id=_id;
   end if;

end;
$$;


ALTER FUNCTION public.editarmarca(_descripcion text, _idempresa integer, _id integer) OWNER TO postgres;


CREATE FUNCTION public.insertarcategorias(_descripcion text, _idempresa integer, _color text) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
   perform 1 from categorias where descripcion =_descripcion and id_empresa=_idempresa;
   if found then
     raise exception 'Datos duplicados';
   else
     insert into categorias(descripcion,id_empresa,color)
     values(_descripcion,_idempresa,_color);
   end if;

end;
$$;


ALTER FUNCTION public.insertarcategorias(_descripcion text, _idempresa integer, _color text) OWNER TO postgres;

CREATE FUNCTION public.insertarmarca(_descripcion text, _idempresa integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
   perform 1 from marca where descripcion =_descripcion and id_empresa=_idempresa;
   if found then
     raise exception 'Datos duplicados';
   else
     insert into marca(descripcion,id_empresa)
     values(_descripcion,_idempresa);
   end if;

end;
$$;


ALTER FUNCTION public.insertarmarca(_descripcion text, _idempresa integer) OWNER TO postgres;
CREATE FUNCTION public.insertarproductos(_descripcion text, _idmarca integer, _stock numeric, _stock_minimo numeric, _codigobarras text, _codigointerno text, _precioventa numeric, _preciocompra numeric, _id_categoria integer, _id_empresa integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
   perform 1 from productos where descripcion =_descripcion and id_empresa=_id_empresa;
   if found then
     raise exception 'Datos duplicados';
   else
     insert into productos(descripcion,idmarca,stock,stock_minimo,codigobarras,codigointerno,precioventa,preciocompra,id_categoria,id_empresa)
     values(_descripcion, _idmarca, _stock, _stock_minimo, _codigobarras, _codigointerno, _precioventa, _preciocompra, _id_categoria, _id_empresa);
   end if;

end;
$$;


ALTER FUNCTION public.insertarproductos(_descripcion text, _idmarca integer, _stock numeric, _stock_minimo numeric, _codigobarras text, _codigointerno text, _precioventa numeric, _preciocompra numeric, _id_categoria integer, _id_empresa integer) OWNER TO postgres;


CREATE FUNCTION public.inventariovalorado(_id_empresa integer) RETURNS TABLE(id integer, descripcion text, stock numeric, preciocompra numeric, total numeric)
    LANGUAGE sql
    AS $$
select id,descripcion,stock,preciocompra,(stock*preciocompra) as total from productos
where productos.id_empresa=_id_empresa;
$$;


ALTER FUNCTION public.inventariovalorado(_id_empresa integer) OWNER TO postgres;
--
-- TOC entry 3722 (class 2606 OID 29867)
-- Name: asignarempresa asignarempresa_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignarempresa
    ADD CONSTRAINT asignarempresa_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 3723 (class 2606 OID 29872)
-- Name: categorias categorias_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 3720 (class 2606 OID 29877)
-- Name: empresa empresa_iduseradmin_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_iduseradmin_fkey FOREIGN KEY (iduseradmin) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 3724 (class 2606 OID 29882)
-- Name: kardex kardex_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kardex
    ADD CONSTRAINT kardex_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id);


--
-- TOC entry 3725 (class 2606 OID 29887)
-- Name: kardex kardex_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kardex
    ADD CONSTRAINT kardex_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 3726 (class 2606 OID 29892)
-- Name: kardex kardex_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kardex
    ADD CONSTRAINT kardex_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- TOC entry 3727 (class 2606 OID 29897)
-- Name: marca marca_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT marca_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 3728 (class 2606 OID 29902)
-- Name: permisos permisos_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 3729 (class 2606 OID 29907)
-- Name: permisos permisos_idmodulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_idmodulo_fkey FOREIGN KEY (idmodulo) REFERENCES public.modulos(id);


--
-- TOC entry 3730 (class 2606 OID 29912)
-- Name: productos productos_id_categoria_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_id_categoria_fkey FOREIGN KEY (id_categoria) REFERENCES public.categorias(id);


--
-- TOC entry 3731 (class 2606 OID 29917)
-- Name: productos productos_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 3732 (class 2606 OID 29922)
-- Name: productos productos_idmarca_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_idmarca_fkey FOREIGN KEY (idmarca) REFERENCES public.marca(id);


--
-- TOC entry 3895 (class 3256 OID 29947)
-- Name: asignarempresa Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable delete for users based on user_id" ON public.asignarempresa FOR DELETE TO authenticated USING ((id = id));


--
-- TOC entry 3896 (class 3256 OID 29948)
-- Name: categorias Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable delete for users based on user_id" ON public.categorias FOR DELETE TO authenticated USING ((id = id));


--
-- TOC entry 3897 (class 3256 OID 29949)
-- Name: empresa Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable delete for users based on user_id" ON public.empresa FOR DELETE TO authenticated USING ((id = id));


--
-- TOC entry 3898 (class 3256 OID 29950)
-- Name: kardex Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable delete for users based on user_id" ON public.kardex FOR DELETE TO authenticated USING ((id = id));


--
-- TOC entry 3899 (class 3256 OID 29951)
-- Name: marca Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable delete for users based on user_id" ON public.marca FOR DELETE TO authenticated USING ((id = id));


--
-- TOC entry 3900 (class 3256 OID 29952)
-- Name: permisos Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable delete for users based on user_id" ON public.permisos FOR DELETE TO authenticated USING ((id = id));


--
-- TOC entry 3901 (class 3256 OID 29953)
-- Name: productos Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable delete for users based on user_id" ON public.productos FOR DELETE TO authenticated USING ((id = id));


--
-- TOC entry 3902 (class 3256 OID 29954)
-- Name: usuarios Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable delete for users based on user_id" ON public.usuarios FOR DELETE TO authenticated USING ((id = id));


--
-- TOC entry 3903 (class 3256 OID 29955)
-- Name: asignarempresa Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable insert for authenticated users only" ON public.asignarempresa FOR INSERT WITH CHECK (true);


--
-- TOC entry 3904 (class 3256 OID 29956)
-- Name: categorias Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable insert for authenticated users only" ON public.categorias FOR INSERT TO authenticated WITH CHECK (true);


--
-- TOC entry 3905 (class 3256 OID 29957)
-- Name: empresa Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable insert for authenticated users only" ON public.empresa FOR INSERT TO authenticated WITH CHECK (true);


--
-- TOC entry 3906 (class 3256 OID 29958)
-- Name: kardex Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable insert for authenticated users only" ON public.kardex FOR INSERT TO authenticated WITH CHECK (true);


--
-- TOC entry 3907 (class 3256 OID 29959)
-- Name: marca Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable insert for authenticated users only" ON public.marca FOR INSERT TO authenticated WITH CHECK (true);


--
-- TOC entry 3908 (class 3256 OID 29960)
-- Name: permisos Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable insert for authenticated users only" ON public.permisos FOR INSERT WITH CHECK (true);


--
-- TOC entry 3909 (class 3256 OID 29961)
-- Name: productos Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable insert for authenticated users only" ON public.productos FOR INSERT TO authenticated WITH CHECK (true);


--
-- TOC entry 3910 (class 3256 OID 29962)
-- Name: usuarios Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable insert for authenticated users only" ON public.usuarios FOR INSERT TO authenticated WITH CHECK (true);


--
-- TOC entry 3911 (class 3256 OID 29963)
-- Name: asignarempresa Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.asignarempresa FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3912 (class 3256 OID 29964)
-- Name: categorias Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.categorias FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3913 (class 3256 OID 29965)
-- Name: empresa Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.empresa FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3914 (class 3256 OID 29966)
-- Name: kardex Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.kardex FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3915 (class 3256 OID 29967)
-- Name: marca Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.marca FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3916 (class 3256 OID 29968)
-- Name: modulos Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.modulos FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3917 (class 3256 OID 29969)
-- Name: permisos Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.permisos FOR SELECT USING (true);


--
-- TOC entry 3918 (class 3256 OID 29970)
-- Name: productos Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.productos FOR SELECT USING (true);


--
-- TOC entry 3919 (class 3256 OID 29971)
-- Name: usuarios Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.usuarios FOR SELECT USING (true);


--
-- TOC entry 3920 (class 3256 OID 29972)
-- Name: asignarempresa Enable update for users based on email; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable update for users based on email" ON public.asignarempresa FOR UPDATE TO authenticated USING ((id = id)) WITH CHECK ((id = id));


--
-- TOC entry 3921 (class 3256 OID 29973)
-- Name: categorias Enable update for users based on email; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable update for users based on email" ON public.categorias FOR UPDATE TO authenticated USING ((id = id)) WITH CHECK ((id = id));


--
-- TOC entry 3922 (class 3256 OID 29974)
-- Name: empresa Enable update for users based on email; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable update for users based on email" ON public.empresa FOR UPDATE TO authenticated USING ((id = id)) WITH CHECK ((id = id));


--
-- TOC entry 3923 (class 3256 OID 29975)
-- Name: marca Enable update for users based on email; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable update for users based on email" ON public.marca FOR UPDATE TO authenticated USING ((id = id)) WITH CHECK ((id = id));


--
-- TOC entry 3924 (class 3256 OID 29976)
-- Name: permisos Enable update for users based on email; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable update for users based on email" ON public.permisos FOR UPDATE TO authenticated USING ((id = id)) WITH CHECK ((id = id));


--
-- TOC entry 3925 (class 3256 OID 29977)
-- Name: productos Enable update for users based on email; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable update for users based on email" ON public.productos FOR UPDATE TO authenticated USING ((id = id)) WITH CHECK ((id = id));


--
-- TOC entry 3926 (class 3256 OID 29978)
-- Name: usuarios Enable update for users based on email; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable update for users based on email" ON public.usuarios FOR UPDATE TO authenticated USING ((id = id)) WITH CHECK ((id = id));

